version: '3'

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ../.local/cmake-container:/workspace/.local/cmake:cached # Override to avoid conflict
      - ../.local/vcpkg-container:/workspace/.local/vcpkg:cached # Override to avoid conflict
    command: sleep infinity
